dist: trusty
language:  cpp
compiler : gcc
notifications:
  slack: spuc:VfvBwrKcCRGX7RWcZBIfXFBr
install:
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq python-dev python-numpy
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
